SADA.Web/Areas/Admin/Controllers/CategoryController.cs
namespace SADA.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CategoryController : Controller
{
    #region Props
    private readonly IUnitOfWork _unitOfWork;
    #endregion

    #region Constructor(s)
    public CategoryController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    #endregion

    #region Actions
    public IActionResult Index() => View();

    public IActionResult Create() => View();

    public IActionResult Edit(int? id)
    {
        if (id is null || id == 0)
            return NotFound();

        var categoryFromDb = _unitOfWork.Category.GetById((int)id);

        if (categoryFromDb is null)
            return NotFound();

        return View(categoryFromDb);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Create(Category obj)
    {
        if (_upsert(obj))
            return RedirectToAction("Index");

        return View(obj);
    }
    
    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Edit(Category obj)
    {
        if (_upsert(obj))
            return RedirectToAction("Index");

        return View(obj);
    }
    #endregion

    #region Helper Methods
    private bool _upsert(Category obj)
    {
        if (obj.Name == obj.DisplayOrder.ToString())
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");

        if (ModelState.IsValid) //depends on constraints in the model
        {
            string key;

            if (obj.Id == 0)
            {
                _unitOfWork.Category.Add(obj);
                key = "Created";

            }
            else
            {
                _unitOfWork.Category.Update(obj);
                key = "updated";
            }
            _unitOfWork.Save();

            TempData["success"] = $"Category {key} successfully";

            return true;
        }
        return false;
    }
    #endregion
}

SADA.Web/Areas/Client/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Net.payOS.Types;
using Net.payOS;
using Stripe.Checkout;
using Twilio.Http;
using Twilio.TwiML.Messaging;


namespace SADA.Web.Areas.Client.Controllers
{
    
    [Area("Client")]
    
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWorks;
        private readonly ISmsSender _SmsSender;
        private readonly ApplicationUser _loggedUser;
        private readonly PaymentController _paymentController;
        private readonly PayOS _payOS;
        private readonly IURLHelper _urlHelper;
        public CartController(IUnitOfWork unitOfWork,
            ISmsSender smsSender,
            IHttpContextAccessor HttpContextAccessor,
            IURLHelper urlHelper,
            PayOS payOS,
            IURLHelper uRLHelper)
        {
            _unitOfWorks = unitOfWork;
            _SmsSender = smsSender;
            _loggedUser = HttpContextAccessor.HttpContext.Session.GetObject<ApplicationUser>(SD.SessionLoggedUser);
            _paymentController = new PaymentController(urlHelper);
            _payOS = payOS;
            _urlHelper = uRLHelper;

        }

        [BindProperty] //for post method
        public ShoppingCartVM ShoppingCartVM { get; set; }

        //---------------------------------- Methods---------------------------------------------------
        [HttpGet]
        public IActionResult Index()
        {
            ShoppingCartVM = UploadCartFromDb();
            return View(ShoppingCartVM);
        }

        [HttpGet]
        public IActionResult Summary()
        {
            ShoppingCartVM = UploadCartFromDb();
            ShoppingCartVM.OrderHeader.Name = _loggedUser.Name;
            ShoppingCartVM.OrderHeader.PhoneNumber = _loggedUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.StreetAddress = _loggedUser.StreetAddress;

            ShoppingCartVM.PaymentMethod = _unitOfWorks.PaymentMethod.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString(),
            });

            ShoppingCartVM.Governorates = _unitOfWorks.Governorate.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString(),
            });

            ShoppingCartVM.Cities = _unitOfWorks.City.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString(),
            });

            return View(ShoppingCartVM);
        }

        [HttpPost, ActionName("Summary"), ValidateAntiForgeryToken]
        public async Task<IActionResult> SummaryPostAsync()
        {
            //OrderHeader
            ShoppingCartVM.OrderHeader.ApplicationUserId = _loggedUser.Id;

            ShoppingCartVM.OrderHeader.OrderStatus = SD.Status.Pending.ToString();

            ShoppingCartVM.OrderHeader.PaymentStatus = SD.Status.Pending.ToString();

            //OrderDetail
            ShoppingCartVM.OrderHeader.Items = new List<OrderDetail>();
            ShoppingCartVM.ListCart = CollectOrderItems();
            foreach (var item in ShoppingCartVM.ListCart)
            {
                OrderDetail orderDetail = new()
                {
                    ProductId = item.ProductId,
                    Count = item.Count,
                    Price = item.Price
                };
                ShoppingCartVM.OrderHeader.Items.Add(orderDetail);
            }

            _unitOfWorks.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWorks.Save();
            var orderId = ShoppingCartVM.OrderHeader.Id;
            HttpContext.Session.SetString("OrderId", orderId.ToString());
            if (orderId == 0)
            {
                return View();
            }
            if (ShoppingCartVM.OrderHeader.PaymentMethodId == SD.PaymentByCardID)
            {

               
                    int orderCode = int.Parse(DateTimeOffset.Now.ToString("ffffff"));

                    List<ItemData> items = new List<ItemData>();
                    foreach (var cartItem in ShoppingCartVM.ListCart)
                    {
                        var item = new ItemData
                        (
                            cartItem.Product.Name,
                            cartItem.Count,
                            (int)(cartItem.Price * 100));
                        items.Add(item);
                    }
                    
                    double totalAmount = ShoppingCartVM.OrderHeader.OrderTotal;
                    PaymentData paymentData = new PaymentData(
                          orderCode,
                          (int)totalAmount,
                          "Thanh toan don hang",
                           items,
                         _urlHelper.Url($"cancel"),
                           _urlHelper.Url($"Client/Cart/OrderConfirmation")
    );
                    CreatePaymentResult createPayment = await _payOS.createPaymentLink(paymentData);

                    return Redirect(createPayment.checkoutUrl);
                
                //catch (System.Exception exception)
                //{
                //    Console.WriteLine(exception);
                //    return Redirect("https://localhost:7136/");
                //}
                //stripe setting
                // Session session = await CheckoutByStripe(ShoppingCartVM.ListCart);

                // await CheckoutByStripe(ShoppingCartVM.ListCart);
                // _unitOfWorks.OrderHeader.UpdateStripePaymentID(ShoppingCartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
                // _unitOfWorks.Save();

                // Response.Headers.Add("Location", session.Url);
                //return new StatusCodeResult(303);
            }
            else if (ShoppingCartVM.OrderHeader.PaymentMethodId == SD.PaymentByCashID)
            {
                return RedirectToAction("OrderConfirmation");
                //OrderConfirmationAsync(ShoppingCartVM.OrderHeader.Id);
            }

            return View();
        }

        [HttpGet("Client/Cart/OrderConfirmation")]
        public async Task<IActionResult> OrderConfirmationAsync()
        {
            var orderIdString = HttpContext.Session.GetString("OrderId");
            int orderId = int.Parse(orderIdString);
            OrderHeader orderHeader = _unitOfWorks.OrderHeader.GetById(orderId);
            if (orderHeader == null)
            {

                return NotFound();
            }
            //if (orderHeader.PaymentMethodId == SD.PaymentByCardID)
            //{
            //    //check the stripe status
            //    var service = new SessionService();
            //    Session session = service.Get(orderHeader.SessionId);
            //    if (session.PaymentStatus.ToLower() != "paid")
            //    {
            //        return RedirectToAction("Summary");
            //    }

            //}

            _unitOfWorks.OrderHeader.UpdateStatus(orderId, SD.Status.Approved.ToString(), SD.Status.Approved.ToString());
            _unitOfWorks.Save();

            //remove shopping cart
            List<ShoppingCart> ListCart = _unitOfWorks.ShoppingCart.GetAll(
                includeProperties: "Product",
                criteria: c => c.UserId == orderHeader.ApplicationUserId
                ).ToList();

            _unitOfWorks.ShoppingCart.RemoveRange(ListCart);
            _unitOfWorks.Save();

            //clear session value for cart
            HttpContext.Session.Remove(SD.SessionCart);

            //send sms message
            await _SmsSender.SendSMSAsync(orderHeader.PhoneNumber, $"Order Placed on Candel Bless. Your OrderID:{orderHeader.Id}");

            return View(orderId);
        }

        public IActionResult Plus(int cartId)
        {
            var cartFromDb = _unitOfWorks.ShoppingCart.GetById(cartId);

            _unitOfWorks.ShoppingCart.IncrementCount(cartFromDb, 1);

            _unitOfWorks.Save();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int cartId)
        {
            var cartFromDb = _unitOfWorks.ShoppingCart.GetById(cartId);
            if (cartFromDb.Count > 1)
            {
                _unitOfWorks.ShoppingCart.DecrementCount(cartFromDb, 1);
            }
            else //delete
            {
                _unitOfWorks.ShoppingCart.Remove(cartFromDb);
                HttpContext.Session.DecrementValue(SD.SessionCart, 1);
            }
            _unitOfWorks.Save();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int cartId)
        {
            var cartFromDb = _unitOfWorks.ShoppingCart.GetById(cartId);

            _unitOfWorks.ShoppingCart.Remove(cartFromDb);

            _unitOfWorks.Save();

            HttpContext.Session.DecrementValue(SD.SessionCart, 1);

            return RedirectToAction(nameof(Index));
        }

        //----------------------------------Helper Methods-------------------------------------------------
        private ShoppingCartVM UploadCartFromDb()
        {
            //get cart
            ShoppingCartVM ShoppingCartVM = new()
            {
                ListCart = CollectOrderItems(),
                OrderHeader = new()
            };
            //calculate total
            foreach (var item in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (item.Price * item.Count);
            }

            return ShoppingCartVM;
        }

        private IEnumerable<ShoppingCart> CollectOrderItems()
        {
            return _unitOfWorks.ShoppingCart.GetAll(
                includeProperties: "Product",
                criteria: c => c.UserId == _loggedUser.Id);
        }

        private async Task<IActionResult> CheckoutByStripe(IEnumerable<ShoppingCart> CartList)
        {

SADA.Web/Areas/Client/Controllers/OrderHistoryController.cs
using Microsoft.AspNetCore.Mvc;
using static SADA.Core.Constants.SD;

namespace SADA.Web.Areas.Client.Controllers
{
    [Area("Client")]
    public class OrderHistoryController : Controller
	{
		
		private readonly IUnitOfWork _unitOfWorks;

		//[BindProperty]
		//public OrderManagementVM OrderManagementVM { get; set; }
		//#endregion

		#region Constructor(s)
		public OrderHistoryController(IUnitOfWork unitOfWork)
		{
			_unitOfWorks = unitOfWork;
		}
		#endregion


		public IActionResult Index()
		{
			IEnumerable<OrderHeader>? orderslist = null;
			
		   orderslist = _unitOfWorks.OrderHeader.GetAll("ApplicationUser", o => o.Id, SD.Descending,criteria: o=>o.ApplicationUserId == HttpContext.Session.GetObject<ApplicationUser>(SD.SessionLoggedUser).Id);
			
			return View(orderslist);
		}
	}
}

SADA.Web/ViewComponents/ShoppingCartViewComponent.cs
namespace SADA.Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //get logged user
            var user = HttpContext.Session.GetObject<ApplicationUser>(SD.SessionLoggedUser);

            if(user != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(
                            criteria: c => c.UserId == user.Id).ToList().Count);
                }
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                return View(0);
            }
        }
    }
}

SADA.Web/Views/Shared/Partial/_MenuBar.cshtml
    <li  class="current-menu-item menu-item-has-children">
        <a class="nav-link" asp-area="Client" asp-controller="Home" asp-action="Index">Home</a>
    </li>
@* <li class="menu-item-has-children has-mega-menu">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Category
    </a>
    <div class="dropdown-menu">
    <a class="dropdown-item" asp-area="Client" asp-controller="Home" asp-action="Tinhdau">Tinh Dầu</a>
    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
    <a class="dropdown-item" asp-area="Admin" asp-controller="OrderManagement" asp-action="Index">Orders</a>
   
    </div>
    </li> *@
<li class="menu-item-has-children has-mega-menu">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Content Management
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="OrderManagement" asp-action="Index">Orders</a>
        @*<div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>*@
        </div>
    </li>
<li class="menu-item-has-children has-mega-menu">
    <a class="nav-link" asp-area="Client" asp-controller="OrderHistory" asp-action="Index">Order History</a>
</li>
    <li class="nav-item">
        <a class=nav-link asp-area="Client" asp-controller="Cart" asp-action="Index">
           @await Component.InvokeAsync("ShoppingCart")
        </a>
    </li>

SADA.Web/Views/Shared/Partial/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
@*<script src="https://cdn.tiny.cloud/1/9em7nfhys4qcobbgjzeg41fz9tmguh4zh3ec2r7exae17qb7/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
      toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
      toolbar_mode: 'floating',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
    });
 </script>*@

SADA.Web/Views/Shared/Partial/_Styles.cshtml
<link rel="stylesheet" href="~/css/bootswatchTheme.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
 